---
# tasks file for user
- name: user remove client.conf if it is there
  file: path=~/.ndn/client.conf state=absent

- name: add user to sudoers
  shell: echo "$SUDO_USER"  'ALL=(ALL:ALL)' 'NOPASSWD' ':' ' ALL'  >> /etc/sudoers
  become: yes
  args:
    executable: /bin/bash

#- name: test shell module
#  shell: cat < /etc/sudoers > /tmp/sudoers
#  become: yes
#  args:
#    executable: /bin/bash
#
#- name: add user to sudoers
#  shell: echo "$SUDO_USER"  'ALL=(ALL:ALL)' 'NOPASSWD' ':' ' ALL'  >> /tmp/sudoers
#  become: yes
#  args:
#    executable: /bin/bash

