#!/bin/bash
ndnping -c 5  /ndn/cn/edu/pkusz 
ndnping -c 5  /ndn/edu/neu 
ndnping -c 5  /ndn/edu/umich 
ndnping -c 5  /ndn/edu/illinois 
ndnping -c 5  /ndn/edu/wustl 
ndnping -c 5  /ndn/edu/memphis 
ndnping -c 5  /ndn/gov/nist 
ndnping -c 5  /ndn/edu/colostate 
ndnping -c 5  /ndn/edu/byu 
ndnping -c 5  /ndn/edu/ucla
ndnping -c 5  /ndn/edu/ucla/remap 
ndnping -c 5  /ndn/edu/uci 
ndnping -c 5  /ndn/org/caida 
ndnping -c 5  /ndn/edu/arizona 
ndnping -c 5  /ndn/br/ufpa 
ndnping -c 5  /ndn/th/ac/msu 
ndnping -c 5  /ndn/th/ac/srru 
ndnping -c 5  /ndn/cn/edu/bupt 
ndnping -c 5  /ndn/cn/edu/tongji 
ndnping -c 5  /ndn/id/ac/ui
ndnping -c 5  /ndn/kr/re/kisti 
ndnping -c 5  /ndn/kr/anyang 
ndnping -c 5  /ndn/jp/ac/osaka-u 
ndnping -c 5  /ndn/jp/waseda 
ndnping -c 5  /ndn/pt/ulusofona/copelabs
ndnping -c 5  /ndn/pt/uminho 
ndnping -c 5  /ndn/es/urjc 
ndnping -c 5  /ndn/it/unipd 
ndnping -c 5  /ndn/ch/unibas 
ndnping -c 5  /ndn/de/uni-goettingen 
ndnping -c 5  /ndn/fr/irt-systemx 
ndnping -c 5  /ndn/fr/lip6 
ndnping -c 5  /ndn/nl/tno 
ndnping -c 5  /ndn/no/ntnu 
