---
# tasks file for NOC

- name: create NOC directories
  file: path=/tmp/NOC/ping_delay_tests state=directory mode=0755

- name: copy ndnping parallel test script
  copy: dest=/tmp/NOC/ping_delay_tests/./getTestbedDelays_ndnping_parallel.sh  src=roles/NOC/files/./getTestbedDelays_ndnping_parallel.sh mode=0755

- name: copy ndnping parallel test prefix list
  copy: dest=/tmp/NOC/ping_delay_tests/./full_prefix_list.txt  src=roles/NOC/files/./full_prefix_list.txt mode=0644

- name: copy ndnping parallel test prefix list (UP)
  copy: dest=/tmp/NOC/ping_delay_tests/./full_prefix_list_UP.txt  src=roles/NOC/files/./full_prefix_list_UP.txt mode=0644

#- cron: name="parallel ndn ping test" user="ndnops" state=present disabled=no minute="15" job="cd /tmp/NOC/ping_delay_tests; ./getTestbedDelays_ndnping_parallel.sh -c 300 -n {{ inventory_hostname }} "
- cron: name="parallel ndn ping test" state=present disabled=no minute="10,20,30,40,50,00" job="cd /tmp/NOC/ping_delay_tests; ./getTestbedDelays_ndnping_parallel.sh -c 300 -n {{ inventory_hostname }} "

