---
- name: configure ndn hosts
  hosts: testbed_hosts

- name: configure ndn routers
  hosts: testbed_rtrs

  roles:
  - {role: 'routing', tags: 'routing'}  # to use the tag, use this option: --tags "routing"
  - {role: 'NOC', tags: 'NOC'}  # to use the tag, use this option: --tags "NOC"
  - {role: 'nfd_rtr', tags: 'nfd_rtr'}  # to use the tag, use this option: --tags "nfd_rtr"
  - {role: 'nlsr', tags: 'nlsr'}  # to use the tag, use this option: --tags "nlsr"
  - {role: 'ndnping', tags: 'ndnping'}  # to use the tag, use this option: --tags "ndnping"
  #- routing
  #- nfd_rtr
  #- nlsr
  #- ndnping
  - {role: 'user', tags: 'user'}
